### PR TITLE
mutate with pip

### PR DESCRIPTION
**Pull request by GonzaloLeyton**
Hi, im doing this pull request because i need this module in pip.
I add a setup.py file and change some things to be working as a module

`$ mutate -f code/file -t test/file`

I tried on my project and worked just fine. Tell me if you need some changes, i can do it for you :)

Thanks!

### CODE REVIEW

**Comment by deefex** [comment]
Thanks for the modifications. I wasn't able to complete the merge request for some reason (bit of a git noob, I'm afraid), but I have echoed and committed your changes into master on my own repo. Hope this works for you.

**Comment by GonzaloLeyton** [comment]
Looks like still have an error there.

You miss that you need to move the `mutators` folder inside `mutate` folder.
Doing that will work again.

Try with `pip install .`

Thanks.

**Comment by GonzaloLeyton** [comment]
Looks like still have an error there.

You miss that you need to move the "mutators" folder inside "mutate" folder.
Doing that will work again.

Try with "pip install . "

Thanks.

2016-09-07 9:13 GMT-03:00 Del Dewar notifications@github.com:

**Comment by deefex** [comment]
Thanks! Updated.

**Pull request closed without merging**
